CampusNabber/Controllers/FlagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CampusNabber;
using CampusNabber.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Threading.Tasks;

namespace CampusNabber.Controllers
{
    [Authorize]
    public class FlagController : Controller
    {
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        //
        // GET: /Flag/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create(Guid postId, string username)
        {
            using (var context = new CampusNabberEntities())
            {
                IEnumerable<FlagPost> previousFlags = context.FlagPosts.Where(flag => flag.username_of_flagger.Equals(User.Identity.Name) && flag.flagged_postitem_id.Equals(postId));
                if (previousFlags.Count() > 0)
                {
                    return View("AlreadyFlagged");
                }
                FlagPost newFlag = new FlagPost { username_of_post = username, flagged_postitem_id = postId, flag_date = DateTime.Now, username_of_flagger = User.Identity.Name };
                return View(newFlag);
            }
        }


        [HttpPost]
        public async Task<ActionResult> Create(FlagPost newFlag)
        {
            using (var context = new CampusNabberEntities())
            {
                if (ModelState.IsValid)
                {
                    newFlag.flag_date = DateTime.Now;
                    newFlag.username_of_flagger = User.Identity.Name;
                    newFlag.object_id = Guid.NewGuid();
                    context.FlagPosts.Add(newFlag);
                    UrlHelper u = new UrlHelper(this.ControllerContext.RequestContext);
                    string url = u.Action("Details", "PostItems", new { id = newFlag.flagged_postitem_id });
                    try
                    {
                        context.SaveChanges();
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e.Message);
                    }
                    await UserManager.SendEmailAsync("df60a819-7b79-49ee-9b18-7c4f32726115", "Post Flagged as Inappropriate", "<h2>The following post has been flagged as inappropriate.</h2><h4>Please address appropriately.</h4><a href=\"" + url + "\">Link to the Post</a>");
                    return View("SuccessfulCreation");
                }
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult RemoveFlags(PostXFlagViewModel model)
        {
            using (var context = new CampusNabberEntities())
            {
                IEnumerable<FlagPost> flags = context.FlagPosts.Where(flag => flag.flagged_postitem_id == model.PostId);
                context.FlagPosts.RemoveRange(flags);
                context.SaveChanges();
                return View("~/Views/PostXFlagViewModel/Details.cshtml", model);
            }
        }

    }
}

CampusNabber/Views/Flag/AlreadyFlagged.cshtml
@{
    ViewBag.Title = "Campus Nabber";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Already Reported</h2>

<h4>Our records show that you've already flagged this post.</h4>

CampusNabber/Views/Flag/Create.cshtml
@model CampusNabber.Models.FlagPost
@{
    ViewBag.Title = "Campus Nabber";
}

<h2>Create Flag</h2>

@using (Html.BeginForm("Create", "Flag", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-horizontal container">
        @Html.HiddenFor(model => Model.flagged_postitem_id)
        @Html.HiddenFor(model => Model.username_of_post)
        @Html.HiddenFor(model => Model.username_of_flagger)
        @Html.HiddenFor(model => Model.flag_date)
        <div class="form-group">
            <div class="col-md-12">
                <h3>Why are you flagging this post?</h3>
                @Html.TextAreaFor(model => model.flag_reason, new { @rows="5", @class="form-control" })
                @Html.ValidationMessageFor(model => model.flag_reason, "", new {@class="text-danger"})
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Report" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

CampusNabber/Views/Flag/SuccessfulCreation.cshtml
@{
    ViewBag.Title = "Campus Nabber";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Flagging Successful</h2>
<hr />
<div class="row">
    <h3>The post has been successfully flagged. An administrator will review the post in question.</h3>
</div>
<div class="row">
    <a class="btn btn-default pull-right" href=@Url.Action("MainMarketView", "MarketPlace")> Return to Marketplace </a>
</div>