CampusNabber/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusNabber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public System.Guid object_id { get; set; }
        public string category_name { get; set; }
        public string sub_category_name { get; set; }
    }
}

CampusNabber/Controllers/MarketPlaceController.cs
using CampusNabber.Helpers.SchoolClasses;
using CampusNabber.Models;
using CampusNabber.Utility;
using DatabaseCode.CNQueryFolder;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace CampusNabber.Controllers
{
    [Authorize]
    public class MarketPlaceController : Controller
    {
        private ApplicationUserManager _userManager;

        // GET: MarketPlace
        public ActionResult Index()
        {
           
            
            return View();
        }


        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public MarketPlaceController()
        {
           
        }


        public MarketPlaceController(ApplicationUserManager manager)
        {
            UserManager = manager;
        }



        public ActionResult MainMarketView()
        {
            using (var context = new CampusNabberEntities())
            {
                var market = new MarketPlace(UserManager.FindById(User.Identity.GetUserId()));

                ApplicationUser user = UserManager.FindById(User.Identity.GetUserId());
                School school = context.Schools.Where(d => d.object_id == user.school_id).First();
                market.SchoolToken = school.school_tag;
                market.mainSchoolColor = school.main_hex_color;
                //market.school_names.Add(school.school_name);
                if (Session["Color"] == null)
                    Session["Color"] = school.main_hex_color;
                market.setList();
                Session["addSchoolView"] = "MainMarket";
                return View(market);
            }
        }

        [HttpPost]
        public ActionResult SearchSite(String Search)
        {
            if(Search.Length <1)
              return RedirectToAction("MainMarketView");
            else
                return RedirectToAction("MainMarketView");
        }

        

        [HttpPost]
        public ActionResult AddAdditionalSchools(MarketPlace market)
        {
            var newMarket = new MarketPlace(UserManager.FindById(User.Identity.GetUserId()));
            newMarket.setCategoryNames();
            string fromView = (string)Session["addSchoolView"];
            if (fromView.Equals("Category"))
            {
                if (market.subCategoryToDisplay == null)
                {
                    if (market.categoryToDisplay != null)
                    {
                        newMarket.chosenCategory = newMarket.CategoryNames[(int)market.categoryToDisplay];
                    }
                    else
                        newMarket.chosenCategory = "All Categories";
                    }
                else
                {
                    newMarket.chosenCategory = newMarket.CategoryNames[(int)market.categoryToDisplay];
                    newMarket.chosenSubCategory = newMarket.SubCategoryNames[(int)market.categoryToDisplay].ElementAt((int)market.subCategoryToDisplay);
                }
                string searchCondition = (string)Session["searchString"];
                if (searchCondition != null)
                {
                    newMarket.searchString = searchCondition;
                    //Session.Remove("searchString");
                }
            }
            for (int i = 0; i < market.selectSchool.Count(); i++)
            {
                if (market.selectSchool[i])
                {
                    newMarket.selectSchool[i] = true;
                    newMarket.school_names.Add(newMarket.otherSchools[i]);
                    //  newMarket.otherSchools.Remove(newMarket.otherSchools[i]);
                }
            }
            //bool GU = Convert.ToBoolean(Request.Form["GU"]);
            //bool WU = Convert.ToBoolean(Request.Form["WU"]);
            
            newMarket.setList();
            if (fromView.Equals("Category"))
            {


                return View("CategoryView", newMarket);
            }
            return View("MainMarketView", newMarket);
        }

        [HttpPost]
        public ActionResult CategoryView(string Search)
        {
            using (var context = new CampusNabberEntities())
            {
                MarketPlace market = new MarketPlace(UserManager.FindById(User.Identity.GetUserId()));
                ApplicationUser user = UserManager.FindById(User.Identity.GetUserId());
                market.setCategoryNames();
                market.chosenCategory = "All Categories";
                School school = context.Schools.Where(d => d.object_id == user.school_id).First();
                market.mainSchoolColor = school.main_hex_color;
                market.searchString = Search;
                Session["addSchoolView"] = "Category";
                Session["searchString"] = Search;
                return View(market);
            }
        }

        public ActionResult CategoryView(MarketPlace market)
        {
            using (var context = new CampusNabberEntities())
            {
                String[] schools = market.schools.Split(',');
                market.school_names = schools.ToList();
                market.setOtherSchools();
                market.setCategoryNames();
                String str = market.otherSchools.ElementAt(0);
                if (market.subCategoryToDisplay == null)
                {
                    market.chosenCategory = market.CategoryNames[(int)market.categoryToDisplay];
                }
                else
                {
                    market.chosenCategory = market.CategoryNames[(int)market.categoryToDisplay];
                    market.chosenSubCategory = market.SubCategoryNames[(int)market.categoryToDisplay].ElementAt((int)market.subCategoryToDisplay);
                }
                ApplicationUser user = UserManager.FindById(User.Identity.GetUserId());
                Session["addSchoolView"] = "Category";

                // market.chosenCategory = market.CategoryNames[(int)market.categoryToDisplay];
                School school = context.Schools.Where(d => d.object_id == user.school_id).First();
                if (Session["Color"] == null)
                    Session["Color"] = school.main_hex_color;
                market.mainSchoolColor = school.main_hex_color;
                market.searchString = "";
                return View(market);
            }
        }



        public JsonResult GetPostItemData(jQueryDataTableParamModel param, String school_names, String user_name, string Category,
            string SubCategory, string Search = "", string FromPrice = "0", string ToPrice = "1000000000", bool HasImage = false)
       {
            using (var context = new CampusNabberEntities())
            {
                String[] schools = school_names.Split(',');
                Guid[] schoolIDS = new Guid[schools.Count()];
                String[] schoolTokens = new String[schools.Count()];
                School school = null;
                Guid schoolID;
                String schoolName;
                
                
                for (int i = 0; i < schools.Count(); i++)
                                    {
                    schoolName = schools[i];
                                        while (schoolName.ElementAt(0) == ' ')
                                           {
                         schoolName = schoolName.Substring(1);
                                            }
                    IQueryable<School> schoo = context.Schools.Where(d => d.school_name == schoolName);
                    school = schoo.First();
                    schoolIDS[i] = school.object_id;
                    schoolTokens[i] = school.school_tag;
                                    }
                
                                 IQueryable < PostItem > postItems = null;
                //IQueryable < PostItem > temp = null;
                var totalRecords = 0;
                var result = new List<PostItemTableModel>();
                var iDisplayRecords = 0;
                for (int i = 0; i < schoolIDS.Count(); i++)
                {
                    schoolID = schoolIDS[i];
                    //  IQueryable<PostItem> postItems = null;


                    if (!string.IsNullOrEmpty(FromPrice) || !string.IsNullOrEmpty(ToPrice))
                    {
                        if (FromPrice.Equals(""))
                            FromPrice = "0";
                        if (ToPrice.Equals(""))
                            ToPrice = "1000000000";
                        int fromPrice = Int32.Parse(FromPrice);
                        int toPrice = Int32.Parse(ToPrice);
                        if (Category.Equals("All Categories"))
                        {
                            postItems = context.PostItems.Where(d =>
                                                          d.price >= fromPrice &&
                                                          d.price <= toPrice &&
                                                          d.username != user_name &&
                                                          d.school_id == schoolID);
                        }
                        else
                        {
                            postItems = context.PostItems.Where(d =>
                                                          d.price >= fromPrice &&
                                                          d.price <= toPrice &&
                                                          d.price <= toPrice &&

CampusNabber/Views/MarketPlace/CategoryView.cshtml
@model CampusNabber.Models.MarketPlace


@{
    ViewBag.Title = "Campus Nabber";
}

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.11/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="~/Content/CategorySheet.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">


<script type="text/javascript" src="~/Scripts/MarketView.js"></script>

@{
    var schoolnames = "";
    for (int i = 0; i < Model.school_names.Count; i++)
    {
        schoolnames += Model.school_names[i];
        if (i + 1 != Model.school_names.Count)
        { schoolnames += ","; }
        Model.schools = schoolnames;
    }
}



    @Html.EditorForModel(Model)
    
        <div class="container" id="customContainer">
            <div class="row col-md-10" >
                <div class="panel-group" id="pageWindow">
                    <div class="panel panel-default">
                        @*
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-sm-2">
                                    <h2>@Model.chosenCategory</h2>
                                    @if(Model.chosenSubCategory != null)
                                    {
                                        <br />
                                        <h2>@Model.chosenSubCategory</h2>
                                    }
                                </div>
                                
                                <div class="col-sm-4">
                                    
                                </div>
                                <div class="col-sm-6">
                                    
                                </div>
                                   

                            </div>
                        </div>
                            *@
                        <div class="panel-body">
                            <div class="col-sm-2">
                                <h2>@Model.chosenCategory</h2>
                                @if (Model.chosenSubCategory != null)
                                {
                                        <h2>@Model.chosenSubCategory</h2>
                                }

                                <fieldset id="searchField" class="myfields">
                                    <form class="form myForm">
                                        <div class="input-group">
                                            <label style="margin-right:2px;" for="fromPrice">From Price:</label>
                                            <input type="text" class="form-control text-box customInput" id="fromPriceInput" name="fromPriceInput" onkeypress='return event.charCode >= 48 && event.charCode <= 57' />
                                        </div>
                                    </form>

                                    <form class="form myForm">
                                        <div class="input-group">
                                            <label style="margin-right:19px;" for="toPrice">To Price:</label>
                                            <input type="text" class="form-control text-box customInput" id="toPriceInput" name="toPriceInput" onkeypress='return event.charCode >= 48 && event.charCode <= 57' />
                                        </div>
                                    </form>

                                    <form class="form myForm">
                                        <div class="input-group">
                                            <label style="margin-right:19px;" for="hasImage">Has Image:</label>
                                            <input type="checkbox" id="hasImageInput" name="hasImageInput"/>
                                        </div>
                                    </form>
                                </fieldset>
                                <form class="block form myForm">
                                    <div class="input-group">
                                        <input type="text" id="searchInput" name="searchInput" value="@Model.searchString" class="form-control text-box customInput " placeholder="Search @Model.chosenCategory" />
                                        <a id="searchButton" class="btn btn-primary" onclick="SearchPostItems();" href="#">Search</a>
                                    </div>
                                </form>

                                @using (Html.BeginForm("AddAdditionalSchools", "MarketPlace", FormMethod.Post, new { @id = "nonHover" }))
                                {
                                    <div id="addAdditionalSchools">
                                        <h4>Add Schools</h4>
                                        <table class="table table-borderless" id="displayTable">
                                            <tbody>

                                                @for (int i = 0; i < Model.selectSchool.Count(); i++)
                                                {
                                                    <tr>
                                                        <td>
                                                            @Html.CheckBoxFor(model => model.selectSchool[i])
                                                            @Html.DisplayFor(model => model.otherSchools[i])
                                                            @Html.HiddenFor(model => model.categoryToDisplay)
                                                            @Html.HiddenFor(model => model.subCategoryToDisplay)
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                        
                                        
                                    </div>
                                    <input type="submit" value="Update" />
                                }

                            </div>
                            <div class="col-sm-10">

                                <div class="box">
                                    <div class="box-content padded">

                                        <form method="Post" id="Detail1Validate">
                                            <div id="dataTables">
                                                <table id="PostItemTable" align="right" cellpadding="0" cellspacing="20px" border="0" style="font-size: 18px; width:auto; border: 0px solid #d9d9d9">
                                                    <thead>
                                                        <tr>
                                                            <th style="font-weight: bold;">PostItemID</th>
                                                            <th style="font-weight: bold;">Photo</th>
                                                            <th style="font-weight: bold; text-align:center">Title</th>
                                                            <th style="font-weight: bold; text-align:center">Price</th>

                                                        </tr>
                                                    </thead>
                                                    <tbody></tbody>
                                                </table>
                                            </div>
                                            <br />
                                            <br />
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>   
    </div>

 


        <script>

           // alert(schoolnames);
            function SearchPostItems() {
               // debugger;
                oTable.fnReloadAjax();
            }
          


            var oTable;
            $(function () {
               // debugger;
                oTable = $('#PostItemTable').dataTable({
                    "sPaginationType": "full_numbers",
                    "bInfo": true,
                    "bScrollCollapse": true,
                    "bPaginate": true,
                    "bServerSide": true,
                    "iDisplayLength": 10,
                    "scrollCallapse": true,
                    "oLanguage": {    "sLengthMenu": "_MENU_ records per page",
                        "oPaginate": {
                            "sPrevious": "Prev",
                            "sNext": "Next"
                        }
                    },
                    "scrollY": '50vh',
                    "aoColumnDefs": [
                            { 'bSortable': false, 'aTargets': [ 1, 2 ] }
                    ],
                    "bFilter": false,
                    "sAjaxSource": "@Url.Action("GetPostItemData", "MarketPlace")",
                    "fnServerParams": function (aoData) {
                        aoData.push(
                            { name: "school_names", value: '@Model.schools' },
                            { name: "user_name", value: '@Model.user_name' },
                            { name: "Category", value: '@Model.chosenCategory' },
                            { name: "SubCategory", value:'@Model.chosenSubCategory' },
                            { name: "Search", value: $('#searchInput').val() },
                            { name: "FromPrice", value: $('#fromPriceInput').val() },
                            { name: "ToPrice", value: $('#toPriceInput').val() },
                            { name: "HasImage", value: $('#hasImageInput').is(':checked') }
                            );
                    },
                    "bProcessing": true,
                    "aoColumns": [
                        {
                            "mDataProp": "PostItemID",
                            "sWidth": "10px",
                            "bSortable": false,
                            "visible": false
                        },
                        {
                            "mDataProp": "PhotoPath", "sWidth": "10px",
                            "render": function (mDataProp, type, row) {
                                return '<img src="' + mDataProp + '"style="width=10px;height=10px;" />';
                        }
                        },
                        { "mDataProp": "Title", "sWidth": "100px", "sClass": "alignCenter" },
                        { "mDataProp": "Price", "sWidth": "120px", "sClass": "alignCenter" }
                    ],
                    "fnDrawCallback": function (oSettings) {
                        $('#PostItemTable tbody tr').click(function () {
                            var postItemID = $(this).attr('id');
                            postItemSelected(postItemID);
                        }).css('cursor', 'pointer');
                    },
                    "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                        $(nRow).attr('id', aData.PostItemID);
                    }
                });
            });

            function postItemSelected(id) {
              //  debugger;
               var link = '@Url.Action("Details", "PostItems", new { id = "-1" })';
                link = link.replace("-1", id);
                window.location.href = link;
            }

            function keypressHandler(e) {
               // alert(e.which);
                if (e.which == 13) {
                    e.preventDefault(); //stops default action: submitting form
                    $(this).blur();
                    $('#searchButton').focus().click();//give your submit an ID
                }
            }

            $('.myForm').keypress(keypressHandler);

        </script>