CampusNabber/Models/Ad.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusNabber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public System.Guid object_id { get; set; }
        public string company_name { get; set; }
        public string photo_path_160x600 { get; set; }
        public string photo_path_468x60 { get; set; }
        public string photo_path_728x90 { get; set; }
        public string photo_link { get; set; }
    }
}

CampusNabber/Controllers/AdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.Entity;
using System.Net;
using CampusNabber.Models;
using CampusNabber.Utility;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Web;
using System.Web.Mvc;

namespace CampusNabber.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AdController : Controller
    {


        ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public AdController(ApplicationUserManager _userManager)
        {
            UserManager = _userManager;
        }
        public AdController()
        {

        }

        public ActionResult Index()
        {
            using (var context = new CampusNabberEntities())
            {
                context.Ads.ToList();
                List<AdModel> adModels = new List<AdModel>();
                foreach (Ad ad in context.Ads.ToList())
                {
                    adModels.Add(AdModel.BindToAdModel(ad));
                }
                return View(adModels);
            }
        }

        // Get: /PostItems/Create
        public ActionResult Create()
        {
            AdModel ad = new AdModel();
            return View(ad);
        }

        public ActionResult Details(AdModel adModel)
        {
            List<string> imageURLs = AdService.GetS3Photos(adModel);
            if(imageURLs.Count >= 3)
            {
                ViewBag.firstPhotoPath = imageURLs.ElementAt(0);
                ViewBag.secondPhotoPath = imageURLs.ElementAt(1);
                ViewBag.thirdPhotoPath = imageURLs.ElementAt(2);
            } 
            return View(adModel);
        }

        //Post /PostItems/Create
        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult Create([Bind(Include = "object_id,company_name,photo_link")] AdModel adModel, HttpPostedFileBase image1, 
            HttpPostedFileBase image2, HttpPostedFileBase image3)
        {
            using (var context = new CampusNabberEntities())
            {
                Ad ad = null;
                if (ModelState.IsValid)
                {
                    if (image1 == null || image2 == null || image3 == null)
                    {
                        ViewBag.errorTitle = "File Not Found";
                        ViewBag.errorMsg = "One or more of the submitted photos were not uploaded properly.";
                        return View("~/Views/Admin/AdminError.cshtml");
                    }
                    adModel.object_id = Guid.NewGuid();
                    adModel.photo_path_160x600 = adModel.object_id.ToString() + "/160x600";
                    adModel.photo_path_468x60 = adModel.object_id.ToString() + "/468x60";
                    adModel.photo_path_728x90 = adModel.object_id.ToString() + "/728x90";
                    ad = adModel.BindAd();

                    //****AWS Portion**************
                    AdService.StoreS3Photos(image1, image2, image3, ad);
                    //******************************

                    context.Ads.Add(ad);
                    context.SaveChanges();

                    return RedirectToAction("AdminTools", "Admin");
                }
                return View(ad);
            }
        }

        // POST: PostItems/Delete
        public ActionResult Delete(Guid? id)
        {
            using (var context = new CampusNabberEntities())
            {
                Ad adTemp = context.Ads.Find(id);
                AdModel ad = AdModel.BindToAdModel(adTemp);

                context.Ads.Remove(adTemp);

                //Delete AWS Photos    
                AdService.DeleteS3Photos(ad);

                context.SaveChanges();

                return RedirectToAction("Index");
            }
        }


    }
}

CampusNabber/Views/Ad/Create.cshtml
@model CampusNabber.Models.AdModel


@{
    ViewBag.Title = "Campus Nabber";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <h2>Create a New Ad</h2>

        @using (Html.BeginForm("Create", "Ad", FormMethod.Post,
                                            new { enctype = "multipart/form-data" }))
        {
            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <label class="control-label col-md-2">Company Name</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.company_name, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.company_name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Ad URL</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.photo_link, new { htmlAttributes = new { @class = "form-control", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.photo_link, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Ad Image - 160x600px</label>

                    <div class="col-md-10">
                            <input type="file" name="image1" accept="image/*" multiple required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ad Image - 468x60px</label>

                    <div class="col-md-10">
                            <input type="file" name="image2" accept="image/*" multiple required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ad Image - 728x90</label>

                    <div class="col-md-10">
                            <input type="file" name="image3" accept="image/*" multiple required>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>
@*
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")

        <link rel="stylesheet" href="~/Content/School.css" type="text/css" />

        <script type="text/javascript">
                var mainColor = '@(ViewBag.main_color)';
                var secondaryColor = '@(ViewBag.secondary_color)';

        </script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/SchoolColor.js")"></script>

    }
*@

CampusNabber/Views/Ad/Details.cshtml
@model CampusNabber.Models.AdModel
@{
    ViewBag.Title = "Campus Nabber";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container row">
    <h2>Ad Details<a class="btn btn-default pull-right" href="@Url.Action("AdminTools", "Admin")">Back to Admin Tools</a></h2>
</div>
<hr/>
<div class="container">
    <div class="row">
        <dl>
            <dt>Company Name </dt>
            <dd> @Model.company_name </dd>
            <dt>Redirect URL</dt>
            <dd>@Model.photo_link</dd>
        </dl>
    </div>
    <div class="row">
        <div class="col-md-4">
            <label>Ad Image - 160x600</label>
            <img src="@ViewBag.firstPhotoPath" />
        </div>
        <div class="col-md-4">
            <label>Ad Image - 468x60</label>
            <img src="@ViewBag.secondPhotoPath" />
        </div>
        <div class="col-md-4">
            <label>Ad Image - 728x90</label>
            <img src="@ViewBag.thirdPhotoPath" />
        </div>
    </div>
    <div class="row">
            <a class="btn btn-danger pull-right" href="@Url.Action("Delete", "Ad", new { id = Model.object_id })">Delete Ad</a>
    </div>
</div>

CampusNabber/Views/Ad/Index.cshtml
@model IEnumerable<CampusNabber.Models.AdModel>
@{
    ViewBag.Title = "Campus Nabber";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Rotating Ads</h2>
<hr/>
<table class="table">
<thead>
    <tr>
        <th>
            Company Name
        </th>
        <th>
            Ad URL
        </th>
    </tr>
</thead>
    <tbody>
        @foreach(CampusNabber.Models.AdModel ad in Model)
        {
            <tr>
                <td>
                    <a href="@Url.Action("Details","Ad", ad)">
                        @ad.company_name
                    </a>
                </td>
                <td>
                    @ad.photo_link
                </td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-default" href="@Url.Action("AdminTools", "Admin")">Back to Admin Tools</a>
<a class="btn btn-default" href="@Url.Action("Create", "Ad")">Create a New Ad</a>