CampusNabber/Models/PostItem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusNabber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostItem
    {
        public System.Guid object_id { get; set; }
        public string username { get; set; }
        public System.DateTime post_date { get; set; }
        public short price { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public Nullable<System.Guid> school_id { get; set; }
        public Nullable<System.Guid> photo_path_id { get; set; }
        public bool social_flag { get; set; }
    }
}

CampusNabber/Controllers/PostItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampusNabber.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity.Validation;
using System.Diagnostics;
using CampusNabber.Utility;
using CampusNabber.Helpers.SchoolClasses;
using DatabaseCode.FactoryFiles;
using System.Linq.Dynamic;
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using System.Configuration;
using System.IO;
using System.Collections;
using Newtonsoft.Json;

namespace CampusNabber.Controllers
{
    [Authorize]
    public class PostItemsController : Controller
    {
        ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public PostItemsController(ApplicationUserManager _userManager)
        {
            UserManager = _userManager;
        }

        // GET: PostItems
        public ActionResult Index()
        {
            using (var context = new CampusNabberEntities())
            {
                return View(context.PostItems.ToList());
            }
        }

        public PostItemsController()
        {

        }


        // GET: PostItems/Details
        public ActionResult Details(Guid? id)
        {
            using (var context = new CampusNabberEntities())
            {
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    PostItem postItemTemp = context.PostItems.Find(id);
                    PostItemModel postItem = null;
                    if (postItemTemp == null)
                    {
                        AdPostItem adPostItemTemp = context.AdPostItems.Find(id);
                        postItem = AdPostItemViewModel.bindToPostItemModel(adPostItemTemp);
                        if (postItem == null)
                        {
                            return HttpNotFound();
                        }
                    }
                    else
                    {
                        postItem = PostItemModel.bindToModel(postItemTemp);
                    }

                    if (postItem == null)
                    {
                        AdPostItem adPostItemTemp = context.AdPostItems.Find(id);
                        postItem = AdPostItemViewModel.bindToPostItemModel(adPostItemTemp);
                        if (postItem == null)
                        {
                            return HttpNotFound();
                        }
                    }

                    //Builds the school class for create page.
                    School school = context.Schools.Where(d => d.school_name == postItem.school_name).First();
                    ViewBag.main_color = school.main_hex_color;
                    ViewBag.secondary_color = school.secondary_hex_color;
                    ApplicationUser user = UserManager.FindById(User.Identity.GetUserId());
                    if (postItem.photo_path_id.HasValue)
                    {
                        //Check to see whether the PostItemPhotos are stored in the database. This shouldn't happen in the future, but
                        //there are a couple of currently broken posts.
                        List<PostItemPhotos> queryResult = context.PostItemPhotos.Where(d => d.object_id == postItem.photo_path_id).ToList();
                        if (queryResult.Count > 0)
                        {
                            PostItemPhotos postItemPhotos = queryResult.First();
                            //*******AWS Portion *********************
                            List<string> photoList = PostItemService.GetS3Photos(postItem);
                            if (photoList != null && photoList.Count > 0)
                            {
                                ViewBag.RESULTS = photoList;
                                ViewBag.FIRSTPHOTO = photoList[0];
                                ViewBag.HASPHOTO = true;
                            }
                            //******************************************
                        }
                        else
                        {
                            ViewBag.HASPHOTO = false;
                        }
                    }
                    else
                    {
                        ViewBag.HASPHOTO = false;
                    }



                    var correspondingUser = UserManager.FindByName(postItem.username);
                    if (correspondingUser != null)
                    {
                        ViewBag.EMAIL = correspondingUser.Email;
                    }
                    else
                    {
                        ViewBag.EMAIL = "";
                    }
                    return View(postItem);
                }
            }

        }

        public JsonResult GetSubCategory(string category)
        {
            using (var context = new CampusNabberEntities())
            {
                String[] categories = context.Categories.Select(d => d.category_name).Distinct().ToArray();
                SelectList categoriesDropdown = null;
                switch (category)
                {
                    case "Eats and Drinks":
                        categoriesDropdown = PostItemService.generateSubCategoryList("Eats and Drinks");
                        break;
                    case "For Sale":
                        categoriesDropdown = PostItemService.generateSubCategoryList("For Sale");
                        break;
                    case "Housing":
                        categoriesDropdown = PostItemService.generateSubCategoryList("Housing");
                        break;
                    case "Jobs":
                        categoriesDropdown = PostItemService.generateSubCategoryList("Jobs");
                        break;
                    case "On Campus":
                        categoriesDropdown = PostItemService.generateSubCategoryList("On Campus");
                        break;
                }

                return Json(new SelectList(categoriesDropdown, "Value", "Text"));
            }
        }


        // Get: /PostItems/Create
        public ActionResult Create(String userId)
        {
            using (var context = new CampusNabberEntities())
            {
                PostItemModel postItem = null;
                if (userId == null)
                    postItem = new PostItemModel { username = User.Identity.GetUserName() };
                else
                    postItem = new PostItemModel { username = userId };

                ViewBag.username = userId;

                SelectList selectCategory = PostItemService.generateCategoryList();
                ViewBag.selectCategory = selectCategory;

                //Builds the school class for create page.
                ApplicationUser user = UserManager.FindByName(postItem.username);
                School school = context.Schools.Where(d => d.object_id == user.school_id).First();
                postItem.school_name = school.school_name;
                ViewBag.main_color = school.main_hex_color;
                ViewBag.secondary_color = school.secondary_hex_color;
                String[] categories = context.Categories.Select(d => d.category_name).Distinct().ToArray();
                ViewBag.categories = categories;

                return View(postItem);
            }
        }

        //Post /PostItems/Create
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create([Bind(Include = 
        "object_id,username,school_name,post_date,price,title,description,photo_path_id,category,subCategory,social_flag")]
        PostItemModel postItemModel, HttpPostedFileBase image1, HttpPostedFileBase image2, HttpPostedFileBase image3)
        {
            using (var context = new CampusNabberEntities())
            {
                PostItem postItem = null;
                if (ModelState.IsValid)
                {
                    School school = context.Schools.Where(d => d.school_name == postItemModel.school_name).First();

                    HttpPostedFileBase[] images = { image1, image2, image3 };
                    images = images.Where(d => d != null).ToArray();

                    //Sets the school_name here
                    ApplicationUser user = UserManager.FindByName(postItemModel.username);
                    postItemModel.school_name = school.school_name;
                    postItemModel.post_date = System.DateTime.Now;
                    postItemModel.object_id = Guid.NewGuid();
                    if (images.Count() > 0)
                        postItemModel.photo_path_id = Guid.NewGuid();
                    else
                        postItemModel.photo_path_id = Guid.Empty;
                    postItem = postItemModel.bindToPostItem();

                    //****AWS Portion**************
                    if (images.Count() > 0)
                        PostItemService.StoreS3Photos(images, postItem);
                    //******************************

                    context.PostItems.Add(postItem);
                    context.SaveChanges();

                    return RedirectToAction("MainMarketView", "MarketPlace");
                }
                return View(postItem);
            }
        }


        // GET: PostItems/Edit
        public ActionResult Edit(Guid? id)
        {
            using (var context = new CampusNabberEntities())
            {
                if (id == null)
                {

CampusNabber/Views/PostItems/Create.cshtml
@model CampusNabber.Models.PostItemModel



@{
    ViewBag.Title = "Campus Nabber";
}
<div class="row">
    <div class="col-md-10">
        <h2>Create a New Post</h2>

       @using (Html.BeginForm("Create", "PostItems", FormMethod.Post,
                                             new { enctype = "multipart/form-data" }))
       {
        
            <div class="form-horizontal" role="form">

                @Html.HiddenFor(model => Model.username)
                @Html.HiddenFor(model => Model.school_name)
                @Html.HiddenFor(model => model.social_flag)

                <hr />
                

                
                @*@Html.ValidationSummary("", new { @class = "text-danger" })*@
                <div class="form-group">
                    <label class="control-label col-md-4">Title</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">

                    <label class="control-label col-md-4">Category</label>
                    <div class="col-md-8">
                        @Html.DropDownListFor(n => n.category, (SelectList)ViewBag.selectCategory, "Select Category",
                       new { style = "height: 40px;" })
                        @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="form-group" id="subCategoryDiv" style="display:none">

                    <label class="control-label col-md-4">Sub Category</label>
                    <div class="col-md-8">
                        @Html.DropDownListFor(n => n.subCategory, new SelectList(string.Empty, "Value", "Text"),
                       "Select Sub Category", new { style = "height: 40px;" })
                        @Html.ValidationMessageFor(model => model.subCategory, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" id="priceDiv" style="display:none">
                    <label class="control-label col-md-4">Price</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-4">Description</label>
                    <div class="col-md-8">

                        @Html.TextAreaFor(model => model.description, new { @rows = "5", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <label class="control-label col-md-4">Images</label>
                        <form action="demo_form.asp">
                            <div class="col-md-8">

                                <input type="file" name="image1" accept="image/*">
                                <input type="file" name="image2" accept="image/*">
                                <input type="file" name="image3" accept="image/*">
                                </div>
                        </form>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
           
                </div>
        }

    </div>
    <div class="col-md-2 addSpace red">

    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
@*
    <link rel="stylesheet" href="~/Content/School.css" type="text/css" />

    <script type="text/javascript">
            var mainColor = '@(ViewBag.main_color)';
            var secondaryColor = '@(ViewBag.secondary_color)';

    </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/SchoolColor.js")"></script>
*@
    <script type="text/javascript">


        $(document).ready(function () {
            
            $("#category").change(function () {
                var element = $('#category');
                if (element.val().length > 0) {
                    if (element.val() === 'Eats and Drinks' || element.val() === 'On Campus' || element.val() === 'Jobs') {
                        $('#priceDiv').hide();
                        document.getElementById('social_flag').value = true;
                        //alert(document.getElementById('social_flag').value)
                    }
                    else {
                        $('#priceDiv').show();
                        document.getElementById('social_flag').value = false;
                        //alert(document.getElementById('social_flag').value)
                    }
                    $('#subCategoryDiv').show();
                    $("#subCategory").empty();
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("GetSubCategory")', // we are calling json method

                        dataType: 'json',

                        data: { category: $("#category").val() },
                        // here we are get value of selected country and passing same value
                        //as inputto json method GetStates.

                        success: function (subCategory) {
                            // states contains the JSON formatted list
                            // of states passed from the controller

                            $.each(subCategory, function (i, subCategory) {
                                $("#subCategory").append('<option value="' + subCategory.Value + '">' +
                                     subCategory.Text + '</option>');
                                // here we are adding option for States

                            });
                        },
                        error: function (ex) {
                            alert('Failed to retrieve states.' + ex);
                        }
                    });
                    return false;
                }
                else {
                    $("#subCategory").empty();
                    $('#subCategoryDiv').hide();
                    
                }
            })

            $("#subCategory").change(function () {
                var sc = $('#subCategory');
                var c = $('#category');
                if(c.val() ==='For Sale')
                    if(sc.val() === 'Free')
                    {
                        $('#priceDiv').hide();
                        
                    }
            })

        });
    </script>

}

CampusNabber/Views/PostItems/Delete.cshtml
@model CampusNabber.Models.PostItemModel

@{
    ViewBag.Title = "Campus Nabber";
}
<div class="row">
    <div class="col-md-10">
        <h2>Delete Post</h2>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <hr />
            <dl class="dl-horizontal">

                <dt>
                    Title
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.title)
                </dd>

                <dt>
                    Date Posted
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.post_date)
                </dd>

                <dt>
                    Category
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.category)
                </dd>

                <dt>
                    Price
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.price)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.photo_path_id)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.photo_path_id)
                </dd>

                <dt>
                    Description
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.description)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                    @Html.ActionLink("Back to Profile", "ProfileView", "Profile")
                </div>
            }
        </div>
        </div>
    <div class="col-md-2 addSpace red">

    </div>
</div>

CampusNabber/Views/PostItems/Details.cshtml
@model CampusNabber.Models.PostItemModel

@{
    ViewBag.Title = "Campus Nabber";
}

<header>


    <h2>@Html.DisplayFor(model => model.title)</h2>

    <div class="dropdown pull-right">
        <button class="btn btn-primary dropdown-toggle pull-right" type="button" data-toggle="dropdown">
            Contact
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="mailto:@ViewBag.EMAIL">Email: @ViewBag.EMAIL </a></li>
        </ul>
    </div>

</header>

@section Scripts {
    <script type="text/javascript">
        var mainColor = '@(ViewBag.main_color)';
        var secondaryColor = '@(ViewBag.secondary_color)';

    </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/SchoolColor.js")"></script>
    <link rel="stylesheet" href="~/Content/PostItem.css" type="text/css" />

}

<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js"></script>


<div class="container">
    <div class="row">
        <hr />

        <div class="col-md-6">
            <dl class="dl-horizontal">

                <dt> Posted By </dt>
                <dd> @Html.DisplayFor(model => model.username) </dd>
                <dt> School </dt>
                <dd> @Html.DisplayFor(model => model.school_name) </dd>
                <dt> Date Posted </dt>
                <dd> @Html.DisplayFor(model => model.post_date) </dd>
                @if (!Model.social_flag)
                {
                <dt> Price </dt>
                <dd> @Html.DisplayFor(model => model.price) </dd>
                }
                <dt> Category </dt>
                <dd> @Html.DisplayFor(model => model.category) </dd>
                <dt> Sub Category </dt>
                <dd> @Html.DisplayFor(model => model.subCategory) </dd>
                <dt> Description </dt>
                <dd> @Html.DisplayFor(model => model.description) </dd>


              



            </dl>
        </div>

        <div class="col-md-4">
            @if (ViewBag.HASPHOTO != null)
            { 
            if (ViewBag.HASPHOTO)
            {
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        @{
                            var dataSlideIndex = 0;
                            var results = ViewBag.RESULTS;
                            foreach (var photoPath in results)
                            {
                                <li data-target="#myCarousel" data-slide-to=dataSlideIndex class="active"></li>
                                dataSlideIndex++;
                            }
                        }
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            @{
                                var firstPhoto = ViewBag.FIRSTPHOTO;
                                <div class="item active carouselImage">
                                    <img src=@firstPhoto alt="Chania">
                                </div>
                                var skipFirstPhoto = 0;
                                foreach (var photoPath in ViewBag.RESULTS)
                                {
                                    if (@skipFirstPhoto != 0)
                                    {
                                        <div class="item carouselImage">
                                            <img src=@photoPath alt="Chania">
                                        </div>
                                    }
                                    skipFirstPhoto++;
                                }
                            }
                        </div>
                    </div>
                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                                    }
                                }
        </div>
    </div>

  </div>

<br /><br />

    <div class="row">
        <p>
            @Html.ActionLink("Back to List", "MainMarketView", "MarketPlace")

            @if (User.Identity.Name.Equals(Model.username))
            {
                <a class="btn btn-primary pull-right" href=@Url.Action("Edit", "PostItems", new { id = Model.object_id })>Edit Post</a>
            }
            @if (User.IsInRole("Admin"))
            {
                <a style ="margin-right:20%" class="btn btn-danger pull-right" href="@Url.Action("Delete", "PostItems", new {id = Model.object_id})">Take Down Post</a>
            }
            else
            {
            <a class="btn btn-danger pull-right" href=@Url.Action("Create","Flag", new { postId = Model.object_id, username = Model.username })>
                <span class="glyphicon glyphicon-flag"></span> Report Post
            </a>
            }
        </p>
    </div>

CampusNabber/Views/PostItems/FlaggedPosts.cshtml
@model IEnumerable<CampusNabber.Models.PostItemModel>

@{
    ViewBag.Title = "Campus Nabber";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FlaggedPosts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.school_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.post_date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.photo_path_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tags)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.school_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.post_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.photo_path_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tags)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.object_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.object_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.object_id })
        </td>
    </tr>
}

</table>

CampusNabber/Views/PostItems/Index.cshtml
@model IEnumerable<CampusNabber.Models.PostItemModel>

@{
    ViewBag.Title = "Campus Nabber";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.school_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.post_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.photo_path_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.category)
            </th>
            <th></th>
        </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.school_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.post_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.photo_path_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.category)
            </td>
            <td>
                <!--@Html.ActionLink("Edit", "Edit", new { id = item.object_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.object_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.object_id })-->
            </td>
        </tr>
    }

    </table>
}
else
{
    <h4>No PostItems to display</h4>
}